name: file_update_checker
on: [pull_request]
jobs:
  reviewdog:
    name: file_update_checker
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout target
#        uses: actions/checkout@v2
#        with:
##          ref: ${{ github.base_ref }}
#          ref: master
      - name: Checkout branch
        uses: actions/checkout@v2
#      - uses: actions/checkout@master
#        with:
#          ref: ${{ github.head_ref }}
      - name: Check diff
        env:
          STATIC_FOLDER: static_files
        run: |
          set -e -o pipefail
          (git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF) && STATIC_FILE_DIFF=$(git diff --numstat --diff-filter=CDMRT $GITHUB_BASE_REF -- $STATIC_FOLDER | cut -b 5-1000)
          if [ "$STATIC_FILE_DIFF" != "" ]
            then
              echo "ERROR: Static files were updated or deleted. See below changes."
              echo "$STATIC_FILE_DIFF"
              exit 1
          fi
