name: static_file_update
on: [pull_request]
jobs:
  reviewdog:
    name: static_file_update
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout target
#        uses: actions/checkout@v2
#        with:
##          ref: ${{ github.base_ref }}
#          ref: master
      - name: Checkout branch
        uses: actions/checkout@v2
#      - uses: actions/checkout@master
#        with:
#          ref: ${{ github.head_ref }}
      - name: Check diff
        run: |
          set -e -o pipefail
          (git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF) && STATIC_FILE_DIFF=$(git diff --numstat --diff-filter=CDMRT $GITHUB_BASE_REF -- static_files | cut -b 5-1000)
          echo "$STATIC_FILE_DIFF"
          if [ "$STATIC_FILE_DIFF" != "" ]
            then
              echo "Static files were updated or deleted"
              exit 1
          fi
